### ISSUE TITLE
CSV filename is not correct in the README.md

### ISSUE THREAD

**Issue by marcovn** [weltan/cloudbleed-1password#4]
Hi,

The CSV filename should be 'affectedSites.csv', NOT 'affectedItems.csv' as mentioned in the READ.me

Thanks,
marco.

**Comment by marcovn** [comment]
I have raised a PR #7

**Comment by weltan** [comment]
Thanks for the PR, it's merged. I did this very late last night, also THANK YOU for the .gitignore, I almost included my own csv... :)

**Comment by marcovn** [comment]
NO worries. Awesome response to the problem. Glad I could contribute a little.
